version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080